---
authors:
  - "{{ cookiecutter.author }} @{{ cookiecutter.github_username }}"
# Optional dependencies on other collections
dependencies:
  jcook3701.pkgs: "*"
  jcook3701.utils: "*"
  ansible.builtin: "*"
  community.general: ">=8.0.0"
description: >
  {{ cookiecutter.description }}
namespace: {{ cookiecutter.namespace }}
name: {{ cookiecutter.project_name }}
version: {{ cookiecutter.version }}
license:
  - MIT
license_file: LICENSE
readme: ./README.md
tags:
  - lab
  - homelab
  - automation
  - infrastructure
# Optional — minimum Ansible version required
build_ignore:
  - .gitignore
  - .github/
  - tests/
  - docs/
  - scripts/
  - .venv/
repository: >-
  https://github.com/{{ cookiecutter.github_username }}/\
  {{ cookiecutter.github_username }}.{{ cookiecutter.package_name }}
documentation: >-
  https://github.com/{{ cookiecutter.github_username }}/\
  {{ cookiecutter.github_username }}.{{ cookiecutter.package_name }}/blob/main/README.md
homepage: >-
  https://github.com/{{ cookiecutter.github_username }}/\
  {{ cookiecutter.github_username }}.{{ cookiecutter.package_name }}
issues: >-
  https://github.com/{{ cookiecutter.github_username }}/\
  {{ cookiecutter.github_username }}.{{ cookiecutter.package_name }}/issues
...
