# galaxy.yml
{% import '.cookiecutter_includes/license_header.jinja' as license_macros with context -%}
{{- license_macros.license_header(
  cookiecutter.license,
  cookiecutter.author,
  cookiecutter.project_slug,
  file_name='galaxy.yml',
  comment_style='hash') -}}
---
namespace: "{{ cookiecutter.__namespace }}"
name: "{{ cookiecutter.__project_name }}"
version: "{{ cookiecutter.version }}"
authors:
  - "{{ cookiecutter.author }} @{{ cookiecutter.github_username }}"
license:
  - MIT
license_file: LICENSE
readme: ./README.md
description: >
  {{ cookiecutter.description }}

tags:
  - lab
  - homelab
  - automation
  - infrastructure

dependencies:
  jcook3701.pkgs: "*"
  jcook3701.utils: "*"
  ansible.builtin: "*"
  community.general: ">=8.0.0"

build_ignore:
  - .gitignore
  - .github/
  - tests/
  - docs/
  - scripts/
  - .venv/

repository: >-
  https://github.com/{{ cookiecutter.github_username }}/\
  {{ cookiecutter.github_username }}.{{ cookiecutter.project_slug }}
documentation: >-
  https://github.com/{{ cookiecutter.github_username }}/\
  {{ cookiecutter.github_username }}.{{ cookiecutter.project_slug }}/blob/main/README.md
homepage: >-
  https://github.com/{{ cookiecutter.github_username }}/\
  {{ cookiecutter.github_username }}.{{ cookiecutter.project_slug }}
issues: >-
  https://github.com/{{ cookiecutter.github_username }}/\
  {{ cookiecutter.github_username }}.{{ cookiecutter.project_slug }}/issues
...
